version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - namenode-data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
      - "9000:9000"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env

  # Service untuk menjalankan aplikasi Spark
  spark-app:
    build: .
    image: spark-project-final
    container_name: spark-app
    depends_on:
      - namenode
      - datanode
    volumes:
      - .:/home/jovyan/work # Map folder proyek untuk menyimpan hasil .pkl
      - ./data-to-upload:/data # Map folder data untuk diunggah ke HDFS
    command: >
      bash -c "
        set -e;

        echo 'Menunggu HDFS siap (20 detik)...';
        sleep 20;

        # --- PERBAIKAN FINAL DI SINI ---
        # Gunakan path lengkap ke perintah hdfs
        echo 'Membuat direktori /user/fp-bigdata/ptbdb_raw...';
        hdfs dfs -mkdir -p /user/fp-bigdata/ptbdb_raw;

        echo 'Mengunggah data...';
        hdfs dfs -put -f /data/ptbdb_raw/* /user/fp-bigdata/ptbdb_raw/;
        
        echo 'HDFS setup selesai. Memeriksa isi HDFS...';
        echo '------------------ CCTV HDFS ------------------';
        hdfs dfs -ls -R /user;
        echo '---------------------------------------------';
      "

volumes:
  namenode-data:
  datanode-data:
